package br.com.hellodev.moviestreaming.domain.remote.model.country

import kotlinx.serialization.Serializable

@Serializable
data class Country(
    val id: Int? = null,
    val name: String? = null
) {
    companion object {
        val items = listOf(
            Country(id = 1, name = "Afeganistão"),
            Country(id = 2, name = "Albânia"),
            Country(id = 3, name = "Argélia"),
            Country(id = 4, name = "Andorra"),
            Country(id = 5, name = "Angola"),
            Country(id = 6, name = "Antígua e Barbuda"),
            Country(id = 7, name = "Argentina"),
            Country(id = 8, name = "Armênia"),
            Country(id = 9, name = "Austrália"),
            Country(id = 10, name = "Áustria"),
            Country(id = 11, name = "Azerbaijão"),
            Country(id = 12, name = "Bahamas"),
            Country(id = 13, name = "Bahrein"),
            Country(id = 14, name = "Bangladesh"),
            Country(id = 15, name = "Barbados"),
            Country(id = 16, name = "Bielorrússia"),
            Country(id = 17, name = "Bélgica"),
            Country(id = 18, name = "Belize"),
            Country(id = 19, name = "Benin"),
            Country(id = 20, name = "Butão"),
            Country(id = 21, name = "Bolívia"),
            Country(id = 22, name = "Bósnia e Herzegovina"),
            Country(id = 23, name = "Botsuana"),
            Country(id = 24, name = "Brasil"),
            Country(id = 25, name = "Brunei"),
            Country(id = 26, name = "Bulgária"),
            Country(id = 27, name = "Burquina Faso"),
            Country(id = 28, name = "Burundi"),
            Country(id = 29, name = "Cabo Verde"),
            Country(id = 30, name = "Camboja"),
            Country(id = 31, name = "Camarões"),
            Country(id = 32, name = "Canadá"),
            Country(id = 33, name = "República Centro-Africana"),
            Country(id = 34, name = "Chade"),
            Country(id = 35, name = "Chile"),
            Country(id = 36, name = "China"),
            Country(id = 37, name = "Colômbia"),
            Country(id = 38, name = "Comores"),
            Country(id = 39, name = "Congo (Brazzaville)"),
            Country(id = 40, name = "Costa Rica"),
            Country(id = 41, name = "Croácia"),
            Country(id = 42, name = "Cuba"),
            Country(id = 43, name = "Chipre"),
            Country(id = 44, name = "Tchéquia (República Tcheca)"),
            Country(id = 45, name = "Dinamarca"),
            Country(id = 46, name = "Djibouti"),
            Country(id = 47, name = "Dominica"),
            Country(id = 48, name = "República Dominicana"),
            Country(id = 49, name = "Equador"),
            Country(id = 50, name = "Egito"),
            Country(id = 51, name = "El Salvador"),
            Country(id = 52, name = "Guiné Equatorial"),
            Country(id = 53, name = "Eritreia"),
            Country(id = 54, name = "Estônia"),
            Country(id = 55, name = "Eswatini (ex-Suazilândia)"),
            Country(id = 56, name = "Etiópia"),
            Country(id = 57, name = "Fiji"),
            Country(id = 58, name = "Finlândia"),
            Country(id = 59, name = "França"),
            Country(id = 60, name = "Gabão"),
            Country(id = 61, name = "Gâmbia"),
            Country(id = 62, name = "Geórgia"),
            Country(id = 63, name = "Alemanha"),
            Country(id = 64, name = "Gana"),
            Country(id = 65, name = "Grécia"),
            Country(id = 66, name = "Granada"),
            Country(id = 67, name = "Guatemala"),
            Country(id = 68, name = "Guiné"),
            Country(id = 69, name = "Guiné-Bissau"),
            Country(id = 70, name = "Guiana"),
            Country(id = 71, name = "Haiti"),
            Country(id = 72, name = "Santa Sé (Vaticano)"),
            Country(id = 73, name = "Honduras"),
            Country(id = 74, name = "Hungria"),
            Country(id = 75, name = "Islândia"),
            Country(id = 76, name = "Índia"),
            Country(id = 77, name = "Indonésia"),
            Country(id = 78, name = "Irã"),
            Country(id = 79, name = "Iraque"),
            Country(id = 80, name = "Irlanda"),
            Country(id = 81, name = "Israel"),
            Country(id = 82, name = "Itália"),
            Country(id = 83, name = "Jamaica"),
            Country(id = 84, name = "Japão"),
            Country(id = 85, name = "Jordânia"),
            Country(id = 86, name = "Cazaquistão"),
            Country(id = 87, name = "Quênia"),
            Country(id = 88, name = "Kiribati"),
            Country(id = 89, name = "Coreia do Norte"),
            Country(id = 90, name = "Coreia do Sul"),
            Country(id = 91, name = "Kuwait"),
            Country(id = 92, name = "Quirguistão"),
            Country(id = 93, name = "Laos"),
            Country(id = 94, name = "Letônia"),
            Country(id = 95, name = "Líbano"),
            Country(id = 96, name = "Lesoto"),
            Country(id = 97, name = "Libéria"),
            Country(id = 98, name = "Líbia"),
            Country(id = 99, name = "Liechtenstein"),
            Country(id = 100, name = "Lituânia"),
            Country(id = 101, name = "Luxemburgo"),
            Country(id = 102, name = "Madagascar"),
            Country(id = 103, name = "Malawi"),
            Country(id = 104, name = "Malásia"),
            Country(id = 105, name = "Maldivas"),
            Country(id = 106, name = "Mali"),
            Country(id = 107, name = "Malta"),
            Country(id = 108, name = "Ilhas Marshall"),
            Country(id = 109, name = "Mauritânia"),
            Country(id = 110, name = "Maurício"),
            Country(id = 111, name = "México"),
            Country(id = 112, name = "Micronésia"),
            Country(id = 113, name = "Moldávia"),
            Country(id = 114, name = "Mônaco"),
            Country(id = 115, name = "Mongólia"),
            Country(id = 116, name = "Montenegro"),
            Country(id = 117, name = "Marrocos"),
            Country(id = 118, name = "Moçambique"),
            Country(id = 119, name = "Mianmar"),
            Country(id = 120, name = "Namíbia"),
            Country(id = 121, name = "Nauru"),
            Country(id = 122, name = "Nepal"),
            Country(id = 123, name = "Países Baixos"),
            Country(id = 124, name = "Nova Zelândia"),
            Country(id = 125, name = "Nicarágua"),
            Country(id = 126, name = "Níger"),
            Country(id = 127, name = "Nigéria"),
            Country(id = 128, name = "Macedônia do Norte"),
            Country(id = 129, name = "Noruega"),
            Country(id = 130, name = "Omã"),
            Country(id = 131, name = "Paquistão"),
            Country(id = 132, name = "Palau"),
            Country(id = 133, name = "Estado da Palestina"),
            Country(id = 134, name = "Panamá"),
            Country(id = 135, name = "Papua Nova Guiné"),
            Country(id = 136, name = "Paraguai"),
            Country(id = 137, name = "Peru"),
            Country(id = 138, name = "Filipinas"),
            Country(id = 139, name = "Polônia"),
            Country(id = 140, name = "Portugal"),
            Country(id = 141, name = "Catar"),
            Country(id = 142, name = "Romênia"),
            Country(id = 143, name = "Rússia"),
            Country(id = 144, name = "Ruanda"),
            Country(id = 145, name = "São Cristóvão e Nevis"),
            Country(id = 146, name = "Santa Lúcia"),
            Country(id = 147, name = "São Vicente e Granadinas"),
            Country(id = 148, name = "Samoa"),
            Country(id = 149, name = "San Marino"),
            Country(id = 150, name = "São Tomé e Príncipe"),
            Country(id = 151, name = "Arábia Saudita"),
            Country(id = 152, name = "Senegal"),
            Country(id = 153, name = "Sérvia"),
            Country(id = 154, name = "Seychelles"),
            Country(id = 155, name = "Serra Leoa"),
            Country(id = 156, name = "Singapura"),
            Country(id = 157, name = "Eslováquia"),
            Country(id = 158, name = "Eslovênia"),
            Country(id = 159, name = "Ilhas Salomão"),
            Country(id = 160, name = "Somália"),
            Country(id = 161, name = "África do Sul"),
            Country(id = 162, name = "Sudão do Sul"),
            Country(id = 163, name = "Espanha"),
            Country(id = 164, name = "Sri Lanka"),
            Country(id = 165, name = "Sudão"),
            Country(id = 166, name = "Suriname"),
            Country(id = 167, name = "Suécia"),
            Country(id = 168, name = "Suíça"),
            Country(id = 169, name = "Síria"),
            Country(id = 170, name = "Tajiquistão"),
            Country(id = 171, name = "Tanzânia"),
            Country(id = 172, name = "Tailândia"),
            Country(id = 173, name = "Timor-Leste"),
            Country(id = 174, name = "Togo"),
            Country(id = 175, name = "Tonga"),
            Country(id = 176, name = "Trindade e Tobago"),
            Country(id = 177, name = "Tunísia"),
            Country(id = 178, name = "Turquia"),
            Country(id = 179, name = "Turcomenistão"),
            Country(id = 180, name = "Tuvalu"),
            Country(id = 181, name = "Uganda"),
            Country(id = 182, name = "Ucrânia"),
            Country(id = 183, name = "Emirados Árabes Unidos"),
            Country(id = 184, name = "Reino Unido"),
            Country(id = 185, name = "Estados Unidos"),
            Country(id = 186, name = "Uruguai"),
            Country(id = 187, name = "Uzbequistão"),
            Country(id = 188, name = "Vanuatu"),
            Country(id = 189, name = "Venezuela"),
            Country(id = 190, name = "Vietnã"),
            Country(id = 191, name = "Iêmen"),
            Country(id = 192, name = "Zâmbia"),
            Country(id = 193, name = "Zimbábue")
        )
    }
}